##### On va utiliser MLflow pour comparer des modèles de machine learning pour un certain dataset
###### source: https://www.youtube.com/watch?v=VuS2kaqMrf4&t=1163s


In [1]:
from sklearn import datasets
from sklearn.model_selection import train_test_split

In [2]:
dataset = datasets.load_iris()
dataset 

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [3]:
seed = 123
X_train, X_test, y_train, y_test = train_test_split(dataset.data, dataset.target, test_size=0.2, random_state=seed)
X_train.shape

(120, 4)

In [4]:
y_train.shape

(120,)

In [5]:
X_test.shape

(30, 4)

In [6]:
y_test.shape

(30,)

In [7]:
X_test

array([[6.3, 2.5, 4.9, 1.5],
       [6.8, 3. , 5.5, 2.1],
       [6.4, 2.8, 5.6, 2.2],
       [5.6, 3. , 4.1, 1.3],
       [4.9, 3.6, 1.4, 0.1],
       [6. , 3. , 4.8, 1.8],
       [6.3, 2.3, 4.4, 1.3],
       [4.4, 3.2, 1.3, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [5.5, 2.6, 4.4, 1.2],
       [6.9, 3.1, 5.1, 2.3],
       [5.5, 4.2, 1.4, 0.2],
       [5.2, 2.7, 3.9, 1.4],
       [6.5, 3. , 5.5, 1.8],
       [7.7, 3. , 6.1, 2.3],
       [6.5, 3. , 5.8, 2.2],
       [5.5, 3.5, 1.3, 0.2],
       [4.3, 3. , 1.1, 0.1],
       [6.1, 2.9, 4.7, 1.4],
       [4.8, 3. , 1.4, 0.3],
       [5.2, 3.4, 1.4, 0.2],
       [6.3, 2.8, 5.1, 1.5],
       [4.8, 3.4, 1.9, 0.2],
       [6.1, 3. , 4.9, 1.8],
       [5.1, 3.8, 1.6, 0.2],
       [5.4, 3.4, 1.7, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.6, 2.8, 4.9, 2. ],
       [7.7, 3.8, 6.7, 2.2],
       [5. , 3.6, 1.4, 0.2]])

In [12]:
from sklearn.linear_model import LogisticRegression

# on applique mlflow
import mlflow
mlflow.set_experiment("Reg_Logistic_Models") # definir une expérience
mlflow.sklearn.autolog() #permet de utiliser l'API sklearn de mlflow

# Premier run
with mlflow.start_run(run_name= 'reg_logistic_defaut'):

    clf = LogisticRegression()
    clf.fit(X_train,y_train)

2023/12/14 19:30:29 INFO mlflow.tracking.fluent: Experiment with name 'Reg_Logistic_Models' does not exist. Creating a new experiment.
/home/flores-cuba/.local/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [26]:
# Second run
with mlflow.start_run(run_name= 'reg_logistic_max_iter200'):

    clf2 = LogisticRegression(max_iter= 200)
    clf2.fit(X_train,y_train)


In [24]:
from sklearn.tree import DecisionTreeClassifier

mlflow.set_experiment("Decision_Tree_Models")
mlflow.sklearn.autolog()

with mlflow.start_run(run_name= "dt_defaut"):
    dt = DecisionTreeClassifier(random_state= seed)
    dt.fit(X_train, y_train)

In [27]:
with mlflow.start_run(run_name= "dt_max_depth3"):
    dt2 = DecisionTreeClassifier(random_state= seed, max_depth=3)
    dt2.fit(X_train, y_train)

In [17]:
import numpy as np
new_data = np.array([[5.5, 3.8, 4.6, 1.9]])
new_data

array([[5.5, 3.8, 4.6, 1.9]])

In [21]:
#Prediction
import mlflow
logged_model = 'runs:/070274833e7d41a196029cc3a38749a6/model'

# Load model as a PyFuncModel.
loaded_model = mlflow.pyfunc.load_model(logged_model)

# Predict on a Pandas DataFrame.
import pandas as pd
prediction = loaded_model.predict(new_data)
prediction

array([1])

In [28]:
from pyngrok import ngrok
# terminate open tunnels if exist
ngrok.kill()

#Setting the authtoken(optional)

NGROK_AUTH_TOKEN = "2ZXnZGfMWRTNjiVW4rUoGt1TkwO_2B7pTfrkpT2znbtbwPABM"
ngrok.set_auth_token(NGROK_AUTH_TOKEN)

# Open an HTTPs tunnel on port 5000 for http://localhost:5000
ngrok_tunnel = ngrok.connect(addr="5000", proto="http", bind_tls=True)
print("MLflow Tracking UI:", ngrok_tunnel.public_url)

MLflow Tracking UI: https://b42f-2a02-8428-61e6-8101-ab3c-68cb-34c5-4ca1.ngrok-free.app


In [29]:
!mlflow ui

[2023-12-14 21:30:31 +0100] [17150] [INFO] Starting gunicorn 21.2.0
[2023-12-14 21:30:31 +0100] [17150] [INFO] Listening at: http://127.0.0.1:5000 (17150)
[2023-12-14 21:30:31 +0100] [17150] [INFO] Using worker: sync
[2023-12-14 21:30:31 +0100] [17151] [INFO] Booting worker with pid: 17151
[2023-12-14 21:30:31 +0100] [17152] [INFO] Booting worker with pid: 17152
[2023-12-14 21:30:31 +0100] [17153] [INFO] Booting worker with pid: 17153
[2023-12-14 21:30:31 +0100] [17154] [INFO] Booting worker with pid: 17154
^C
[2023-12-14 21:36:11 +0100] [17150] [INFO] Handling signal: int
[2023-12-14 21:36:11 +0100] [17153] [INFO] Worker exiting (pid: 17153)
[2023-12-14 21:36:11 +0100] [17152] [INFO] Worker exiting (pid: 17152)
[2023-12-14 21:36:11 +0100] [17154] [INFO] Worker exiting (pid: 17154)
[2023-12-14 21:36:11 +0100] [17151] [INFO] Worker exiting (pid: 17151)
